### ISSUE TITLE
[Feature request] creeck (Cod 4), summit (Cod BO), mission (MW3)

### ISSUE THREAD

**Issue by update-freak** [XLabsProject/iw4x-client#399]
Hi devs,

please add the maps broadcast (Cod 4), creeck (Cod 4),  summit (Cod BO) and mission (MW3) to the official DLCs from IW4x.
I think this great maps should also be added.

**Comment by MrAmos123** [comment]
+1 for Broadcast, I just wish even the new DLC maps that were added were distributed to everyone as right now there's really no incentive to download without already populated servers. :(

**Comment by Dss0** [comment]
Broadcast was considered for DLC9 and works well already. We can't port maps from BO but there is a CoD:O version of summit which we could use. Creek has some serious issues we may or may not be able to fix. Mission won't happen.

**Comment by Rackover** [comment]
Broadcast, District and Ambush are working well with the latest (experimental) version of iw3xport. 
Creek is... not so easy, it puts a strain on the engine because it has an absurd amount of lighting (lighting works very differently in iw4, and the way Creek's geometry is set up is unexpected to iw4). It could be done but requires some work on iw3xport, maybe some manual work too.

Showdown has not been tested. The other cod4 maps are already present as CODO versions!

The other mentioned maps (Mission, Mountain/Summit) require some work to get working with iw4. As of now I do not have time to put that work in, but I may one day 🙂   No promises though!

**Comment by ipkpjersi** [comment]
Hey @Rackover 

Any idea when we might see Broadcast, District, and Ambush in IW4X? It would be an absolute dream having those maps in IW4X and it absolutely sounds possible.

Cheers.

**Comment by Rackover** [comment]
It's on the way! https://github.com/XLabsProject/iw4x-client/pull/427 https://github.com/XLabsProject/iw3x-port/pull/4
Not on the way to be in a DLC I mean (at least for now), but on the way to be buildable by anyone.
You can already download the release artifact of iw3xport and iw4x and build it yourself if you want. Broadcast, Citystreets and Ambush work very well.  If you need help building these maps yourself I can assist you on discord on #iw4x-modding 🙂
![image](https://user-images.githubusercontent.com/33836535/193402432-397d105a-a96b-48ea-a379-75beb5c97722.png)
![image](https://user-images.githubusercontent.com/33836535/193417836-ba185805-1fd9-4aec-8cce-8f6c3ab63381.png)
![image](https://user-images.githubusercontent.com/33836535/193418083-50983efd-3784-44de-81f8-cb64fe2079d4.png)

**Comment by diamante0018** [comment]
Hello, some of the maps in this feature request are already available.
Our new current stance is that we do not allow the community to request new maps to be added to iw4x directly.
However, we provide the tools to our users so they can manually port these maps themselves so perhaps they can finally understand that it is a very hard process.
There is a guide on our website for porting CoD4 maps to IW4x

**Comment by Rackover** [comment]
If you want Mission to be included in the next DLC you can vote here btw!
https://docs.google.com/forms/d/e/1FAIpQLScuo3Pyb1Ihk98ZqmTWz03zaqA2Is96U40YSvhJlPpnNWKpqQ/viewform
