### ISSUE TITLE
All HTTP Endpoints timeout after a 0xC0000005 at 0x00469AD0

### ISSUE THREAD

**Issue by ineedbots** [XLabsProject/iw4x-client#43]
![image](https://user-images.githubusercontent.com/751729/98293151-76d06100-1f73-11eb-9ec9-868d882f5628.png)

The game server still runs just fine, just problematic when you need to serve the modlist for the server.

**Comment by ineedbots** [comment]
Caused by either
https://github.com/XLabsProject/iw4x-client/blob/develop/src/Components/Modules/Download.cpp#L754
https://github.com/XLabsProject/iw4x-client/blob/develop/src/Components/Modules/ServerInfo.cpp#L206

Most likely checking an out of bounds client

**Comment by ineedbots** [comment]
Can recreate the problem when HTTP requesting /info while the map is changing.

SV_GameClientNum_Score shouldn't be called when the map is changing

**Comment by VVLNT** [comment]
> Can recreate the problem when HTTP requesting /info while the map is changing.
> 
> SV_GameClientNum_Score shouldn't be called when the map is changing
> 
> Should be fixed fast as this can be used to effectively DoS a server needing to host its modlist.

Very nice find. I experienced this on my servers for the longest time, but I suppose I never saw the exception address because I host the server headless on Linux with Wine. What I ended up doing was stopping the HTTP server from starting altogether, and created my own server simulating the IW4x one instead. (to fix the "failed to download modlist" error.)

I believe PR #30 attempted to fix this, but only does so for the game's `status` command function, and not for any of the calls in the IW4x code. I'm not sure it does that correctly either, but I'll see if I can create a patch.
