### ISSUE TITLE
Cannot scroll nor select maps with controller

### ISSUE THREAD

**Issue by Perseveruz** [XLabsProject/iw4x-client#461]
I wanted to bring to the devs attention that it is not possible to scroll through/select maps in the main menu with a controller, unless the mouse pointer is placed over the list of maps. I was wondering if in the next fix, full controller support could be added to map selection in the main menu, thereby removing the need for having to move the mouse pointer over the map area. It is not a big deal, but I find that by implementing this fix, the game would ultimately have full controller support.
Thank you for considering this feature/fix.

**Comment by diamante0018** [comment]
I have been told by the person that wrote controller support the following (summed up):
This is a complicated and very very time-consuming feature to add and is not currently under consideration by anyone in the dev team. Considering you can already use the controller in-game for all the things that matter having to switch to the mouse for these circumstances shouldn't be a problem for you.

**Comment by Rackover** [comment]
our custom menus are not very good

**Comment by Laupetin** [comment]
Basically the way the menu support for controllers is currently is by emulating keyboard presses. This of course is not how the console version would do it.

The console version does have custom handling code for controller buttons for each item type in the menus (lists, text fields, buttons, sliders, etc etc).
Additionally the menu files do have custom button handlers in a bunch of places. The PC menus do not have a handler for console buttons however, so those are missing as well.
So the extent you can use controllers in menus right now is the same as what you could achieve by using your keyboard only.

The way to achieve "full controller support" for menus would be to not do the cheap and easy way of tackling the issue as i have which was emulating keyboard presses but actually hooking a large amount of the key handling for menus are even replace it entirely and implement custom logic for controller buttons for every item type.
Then also you would need to override a lot of the vanilla menus to be able to add additional key handlers for controller buttons to make those work as well.

It's not that it is impossible to do, it's just a lot of work and i didn't feel like it was worth the effort personally.
If somebody has a different idea of tackling it or considers it worth the effort, feel free to implement something.

Otherwise i hope i could help you with some background info.

**Comment by Perseveruz** [comment]
thanks a lot for all your feedback, especially to Laupetin for the detailed explanation on how the controller support works, and fully understand how complicated it would be to add controller support to the map selection menu. Keep being awesome!!!!
