### ISSUE TITLE
Is the RCE patched?

### ISSUE THREAD

**Issue by akgh11** [XLabsProject/iw4x-client#464]
Is the RCE patched and can you provide a link to proof?

Thank you to everyone who maintains this project.

Combining this mod with the bots mod immortalizes this game forever.

**Comment by diamante0018** [comment]
Which rce?

**Comment by Rackover** [comment]
A bunch of them are fixed here: https://github.com/XLabsProject/iw4x-client/blob/develop/src/Components/Modules/Security.cpp#L126

**Comment by akgh11** [comment]
@Rackover thank you for your citation!

Would you like to leave any additional comments?

I am trying to document this in order to easily spread the word about the project's safety.

It might be a good idea to put info about the RCE on the project's website or a FAQ somewhere.

Thanks again!

**Comment by Rackover** [comment]
It's a bit hard for me to comment on them because I didn't write any of these! Most often they patch unsafe commands that would allow a user to crash someone's game or server, or to inject commands and/or code into someone else's game. Usually the lack of safety comes from providing a buffer of a size the game does not expect, and the size being checked unproperly by the basegame allows to override or access segments of memory that are not normally used in the scope of that command or function. You can see how the two `MsgReadBitsCompressCheck` functions for instance here, return early if the size of the buffer is abnormally large.

**Comment by diamante0018** [comment]
MSG_ReadBitsCompress:
A stack-based buffer overflow. The game does not check the length of the uncompressed buffer is not larger than the destination buffer.

PartyHost_HandleJoinPartyRequest:
A stack-based buffer overflow. The game does not sanitise the parameters of the join party request causing the game to execute the packet's buffer.

CL_SelectStringTableEntryInDvar_f:
Allows the client to bypass cheat protection on dvars.

G_LogPrintf:
Uncontrolled format string.

NET_DeferPacketToClient:
Buffer overflow causing a crash.
Because IW4x modifies the net code to receive large packets to support the node system, the length of the buffer needs to be checked to avoid a stack-based buffer overflow.
