### ISSUE TITLE
[Feature Request] Send UDP port number to the master server along with the heartbeat

### ISSUE THREAD

**Issue by BuIlDaLiBlE** [XLabsProject/iw4x-client#691]
Currently, the way master server decides what port is supposed to be on the server list is by taking it from the outbound packet from the server itself. All is fine until the network hardware decides to send it from a random port. This can be solved on the server side by using a better networking equipment that allows for this behavior to be configured (if it's not configurable already), but I'd love to see a solution when the server would provide the port to the master server instead. This will of course require an update to the master server, so the prospects of this being implemented seem pretty slim to me, but I've decided to request this nonetheless.

Some other details are in this Discord thread: https://discord.com/channels/219514629703860235/1056277817110831245

**Comment by diamante0018** [comment]
No, this is a user error most likely caused by some misconfiguration.
Working around this issue will cause other problems like having a discrepancy in the set net_port and what the master server sees and sends to other users.

**Comment by Laupetin** [comment]
I don't think this should just be closed like that, at least i don't know if i understood correctly.
So what you are saying is that you did port forward correctly and your server is perfectly reachable under a certain port.
But when your server tries to register itself to the master, the outgoing port is randomly chosen due to being behind a NAT and so the master server takes this random port and assumes it is the port your server is running on?

Is that what you mean? Is there a way to confirm this then? I would assume a usual router would take the same outgoing port if the port is already port forwarded to you anyway. At least it seems like this is the case for most people, right?

**Comment by BuIlDaLiBlE** [comment]
Yeah, that is exactly correct. I'd like to get to the bottom of this, but I think the problem is my particular cheap TP-Link router that has no way to configure this. I was thinking I could try resetting the settings and testing again, but methinks it's a hardcoded behavior.

**Comment by diamante0018** [comment]
Keep in mind that as this appears to be a request for support it should preferably be dealt in the XLabs discord as per guidelines [](https://github.com/XLabsProject/iw4x-client/blob/develop/.github/ISSUE_TEMPLATE/get-help.md)[get-help] document @Laupetin.
And it appears OP is getting assistance there.

**Comment by diamante0018** [comment]
If you think you still want to post about a feature request for this, you may do it here [master](https://github.com/XLabsProject/master).
This is not the right repository for this specific issue as this would also involve the other XLabs clients
