### ISSUE TITLE
sv_mapRotationCurrent does not work

### ISSUE THREAD

**Issue by K-Faktor** [XLabsProject/iw4x-client#697]
Starting from v0.7.3, this dvar function has stopped working sv_mapRotationCurrent
v0.7.7 does not correctly show the next map

**Comment by diamante0018** [comment]
- For "alleged" support queries, you should have used the correct form [get-help](https://github.com/XLabsProject/iw4x-client/blob/develop/.github/ISSUE_TEMPLATE/get-help.md) ((Which suggests using the XLabs discord first)
- The map rotation system was reworked as you can see from the [CHANGELOG.](https://github.com/XLabsProject/iw4x-client/blob/develop/CHANGELOG.md#073---2022-06-23)
- This is *not* a bug, the new system does not use the Dvar anymore.
- For backwards compatibility with the old map votes mods, you can set it but after one map rotation it is cleared.

**Comment by K-Faktor** [comment]
Now the server does not correctly display information about maps.
What prevented this Dvar, how to return?

**Comment by diamante0018** [comment]
You can't return. This is the new behaviour

**Comment by diamante0018** [comment]
You should use sv_mapRotation Dvar instead of sv_mapRotationCurrent

**Comment by K-Faktor** [comment]
> 

That's because of such innovations, now only bots play on servers

**Comment by diamante0018** [comment]
That is indeed like Joel said.
Also, you must change from `sv_mapRotationCurrent` to `sv_mapRotation` if you want a circular list of the map rotation which would be the same as the old behaviour?

**Comment by K-Faktor** [comment]
Take a look at this file
[rconcommands.zip](https://github.com/XLabsProject/iw4x-client/files/10339038/rconcommands.zip)

**Comment by K-Faktor** [comment]
> That is indeed like Joel said. Also, you should change whatever you are using to make use of `sv_mapRotation` instead of `sv_mapRotationCurrent` if you want a circular list of the map rotation which would be the same as the old behaviour?

Yes, as it was before

**Comment by diamante0018** [comment]
If you are able to edit the tool you sent above good for you, otherwise it seems like it's totally not worth it for us to change anything.
The map rotation system now works very well and also supports random map rotation and can go over the Dvar string limit of 1024 characters. We cannot go back for because of your "old" tool, and any effort to add a specific command to show "the next map rotation" will *require* said "old" tool to be edited anyway. Just spice things up and allow players to vote for new maps with a map vote mod or IW4x builtin feature.
It is extrememly unlikely, that anyone cares about the "next map in the rotation" and that lack of said notice drove players away, so your complaint is also dismissed. Good talk. Gonna close this as I do not recognise any bugs or valid feature requests.
