### ISSUE TITLE
[Feature Request] Redesigned map selection menu

### ISSUE THREAD

**Issue by WantedDV** [XLabsProject/iw4x-client#734]
### **What problem will this solve?**

The current alphabetized scroll menu is great, but it would be nice if the maps were a little more organized.

### **What might be a solution?**

Perhaps we could make use of popup menus: one for dlc maps and another for custom user maps. Something like the image below.

![iw4x-map-selection](https://user-images.githubusercontent.com/122710241/214767310-e6b94e1e-79da-4be8-ba1b-ce52cbc40985.PNG)

This is the middle-ground for users who want custom content and those simply looking for a (very much) improved vanilla experience; stock maps are kept up-front, and the rest are grouped into separate menus.

I suggest the DLC menu contain all official and iw4x dlc packs. These are maps that, I assume, a large portion of users will have downloaded so they can be considered safe for server map rotation. Maybe we could even distinguish each dlc pack with small headings and horizontal dividers like the one used in the image. A scrolling menu would look good here.

Maps that are less common amongst players should be placed in the Bonus Maps section. These would be the maps that are installed in the `userfiles` folder.

### **Anything else we should know?**
The menu I have shown above is not functional yet (buttons do nothing). It is based on a ~10 year old mod that I only have a few remnant files for. I am posting this issue in case any community members would like to help out.

**Comment by Rackover** [comment]
I think it's a great idea! The map selection menu has sucked for too long. Having vanilla + stock maps in the two original categories and leaving a third one for the new maps / usermaps is very good imo.

**Comment by reaaLx** [comment]
Hey guys,

heres my attempt on this idea instead of using the scroll list!
it follows a similar layout to blackops 2


![iw4x_xy2pDjgoxm](https://user-images.githubusercontent.com/20619526/219850749-a87e3f2b-6250-4e25-bce2-68f61ccecbc5.png)
![iw4x_rwyZLMfn7x](https://user-images.githubusercontent.com/20619526/219850762-ef51b15d-e244-4fad-9303-85ff2b6f9353.png)
![iw4x_HS8EpUpRwO](https://user-images.githubusercontent.com/20619526/219850763-f39b37c0-ede6-4a5d-b30e-8ee3cf2db5b6.png)
![nuketown](https://user-imag
[ui_mp.zip](https://github.com/XLabsProject/iw4x-client/files/10773710/ui_mp.zip)
es.githubusercontent.com/20619526/219850779-43cb81b2-acf7-4c28-9ce1-95374e3e74d3.jpg)

**Comment by diamante0018** [comment]
This feature has now been implemented in both the develop version, of IW4x and the rawfiles.
It will be included in the next release. Thanks @reaaLx
