### ISSUE TITLE
X Reload button for gamepad without having to use .menu & custom images

### ISSUE THREAD

**Issue by cirklon** [XLabsProject/iw4x-client#849]
when the game provides a prompt to reload your gun, there is no x or square button as there is on console.

**Comment by diamante0018** [comment]
The thing is that making it exactly like it is on the console is not easy.
This feature has been discussed internally some time ago and will not be implemented.
We do not have an interest in spending development time on making the smallest aesthetic feature that has no impact on gameplay.
Feel free to implement it yourself and submit a PR otherwise this won't come from us any time soon.
